language: android
android:
    components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-18

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-18
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-20
    - sys-img-armeabi-v7a-android-21
before_script:
    - echo no | android create avd --force -n test -t android-18 --abi armeabi-v7a
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - echo no | android create avd --force -n test -t android-20 --abi armeabi-v7a
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
