/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jackwink.libsodium.jni;

public interface SodiumConstants {
  public final static int CRYPTO_SIGN_BYTES = 64;
  public final static int CRYPTO_SIGN_SEEDBYTES = 32;
  public final static int CRYPTO_SIGN_PUBLICKEYBYTES = 32;
  public final static int CRYPTO_SIGN_SECRETKEYBYTES = (32+32);
  public final static int CRYPTO_SECRETBOX_KEYBYTES = 32;
  public final static int CRYPTO_SECRETBOX_MACBYTES = 16;
  public final static int CRYPTO_SECRETBOX_NONCEBYTES = 24;
}
