/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.jackwink.libsodium.jni;

public class Sodium implements SodiumConstants {
  public static int sodium_init() {
    return SodiumJNI.sodium_init();
  }

  public static String sodium_version_string() {
    return SodiumJNI.sodium_version_string();
  }

  public static int crypto_sign_keypair(byte[] pk, byte[] sk) {
    return SodiumJNI.crypto_sign_keypair(pk, sk);
  }

  public static int crypto_sign(byte[] sm, int[] smlen_p, byte[] m, long mlen, byte[] sk) {
    return SodiumJNI.crypto_sign(sm, smlen_p, m, mlen, sk);
  }

  public static int crypto_sign_open(byte[] m, int[] mlen_p, byte[] sm, long smlen, byte[] pk) {
    return SodiumJNI.crypto_sign_open(m, mlen_p, sm, smlen, pk);
  }

  public static int crypto_sign_detached(byte[] sig, int[] siglen_p, byte[] m, long mlen, byte[] sk) {
    return SodiumJNI.crypto_sign_detached(sig, siglen_p, m, mlen, sk);
  }

  public static int crypto_sign_verify_detached(byte[] sig, byte[] m, long mlen, byte[] pk) {
    return SodiumJNI.crypto_sign_verify_detached(sig, m, mlen, pk);
  }

  public static int crypto_aead_chacha20poly1305_encrypt(byte[] c, int[] clen, byte[] m, long mlen, byte[] ad, long adlen, byte[] nsec, byte[] npub, byte[] k) {
    return SodiumJNI.crypto_aead_chacha20poly1305_encrypt(c, clen, m, mlen, ad, adlen, nsec, npub, k);
  }

  public static int crypto_aead_chacha20poly1305_decrypt(byte[] m, int[] mlen, byte[] nsec, byte[] c, long clen, byte[] ad, long adlen, byte[] npub, byte[] k) {
    return SodiumJNI.crypto_aead_chacha20poly1305_decrypt(m, mlen, nsec, c, clen, ad, adlen, npub, k);
  }

  public static int crypto_hash_sha256(byte[] out, byte[] in, long inlen) {
    return SodiumJNI.crypto_hash_sha256(out, in, inlen);
  }

  public static int crypto_hash_sha512(byte[] out, byte[] in, long inlen) {
    return SodiumJNI.crypto_hash_sha512(out, in, inlen);
  }

  public static int crypto_generichash_blake2b(byte[] out, long outlen, byte[] in, long inlen, byte[] key, long keylen) {
    return SodiumJNI.crypto_generichash_blake2b(out, outlen, in, inlen, key, keylen);
  }

  public static int crypto_pwhash_scryptsalsa208sha256(byte[] out, long outlen, String passwd, long passwdlen, byte[] salt, long opslimit, long memlimit) {
    return SodiumJNI.crypto_pwhash_scryptsalsa208sha256(out, outlen, passwd, passwdlen, salt, opslimit, memlimit);
  }

  public static int crypto_box_curve25519xsalsa20poly1305_keypair(byte[] pk, byte[] sk) {
    return SodiumJNI.crypto_box_curve25519xsalsa20poly1305_keypair(pk, sk);
  }

  public static void randombytes(byte[] buf, long size) {
    SodiumJNI.randombytes(buf, size);
  }

  public static int crypto_box_curve25519xsalsa20poly1305(byte[] c, byte[] m, long mlen, byte[] n, byte[] pk, byte[] sk) {
    return SodiumJNI.crypto_box_curve25519xsalsa20poly1305(c, m, mlen, n, pk, sk);
  }

  public static int crypto_box_curve25519xsalsa20poly1305_open(byte[] m, byte[] c, long clen, byte[] n, byte[] pk, byte[] sk) {
    return SodiumJNI.crypto_box_curve25519xsalsa20poly1305_open(m, c, clen, n, pk, sk);
  }

  public static int crypto_scalarmult_curve25519(byte[] q, byte[] n, byte[] p) {
    return SodiumJNI.crypto_scalarmult_curve25519(q, n, p);
  }

  public static int crypto_secretbox_xsalsa20poly1305(byte[] c, byte[] m, long mlen, byte[] n, byte[] k) {
    return SodiumJNI.crypto_secretbox_xsalsa20poly1305(c, m, mlen, n, k);
  }

  public static int crypto_secretbox_xsalsa20poly1305_open(byte[] m, byte[] c, long clen, byte[] n, byte[] k) {
    return SodiumJNI.crypto_secretbox_xsalsa20poly1305_open(m, c, clen, n, k);
  }

  public static int crypto_sign_ed25519_seed_keypair(byte[] pk, byte[] sk, byte[] seed) {
    return SodiumJNI.crypto_sign_ed25519_seed_keypair(pk, sk, seed);
  }

  public static int crypto_sign_ed25519(byte[] sm, int[] smlen, byte[] m, long mlen, byte[] sk) {
    return SodiumJNI.crypto_sign_ed25519(sm, smlen, m, mlen, sk);
  }

  public static int crypto_sign_ed25519_open(byte[] m, int[] mlen, byte[] sm, long smlen, byte[] pk) {
    return SodiumJNI.crypto_sign_ed25519_open(m, mlen, sm, smlen, pk);
  }

  public static int crypto_stream_xsalsa20(byte[] c, long clen, byte[] n, byte[] k) {
    return SodiumJNI.crypto_stream_xsalsa20(c, clen, n, k);
  }

  public static int crypto_stream_xsalsa20_xor(byte[] c, byte[] m, long mlen, byte[] n, byte[] k) {
    return SodiumJNI.crypto_stream_xsalsa20_xor(c, m, mlen, n, k);
  }

}
